# Generated by Django 3.1.3 on 2020-11-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
